{
 "title": "Torchserve Dashboard (Test)",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Worker CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 17, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "ts_worker_cpu_usage",
     "legendFormat": "{{ model_name }}, v{{ model_version }} (pid: {{ pid }})"
    }
   ]
  },
  {
   "title": "Worker Memory Usage",
   "type": "piechart",
   "gridPos": { "h": 12, "w": 5, "x": 17, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ts_worker_memory_usage",
     "legendFormat": "\"{{ model_name }}\" PID: {{ pid }}"
    }
   ]
  },
  {
   "title": "Worker Memory MiB",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 17, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "ts_worker_memory_mib",
     "legendFormat": "{{ model_name }}, v{{ model_version }} (pid: {{ pid }})"
    }
   ]
  },
  {
   "title": "Worker Memory Total (MiB)",
   "type": "stat",
   "gridPos": { "h": 6, "w": 5, "x": 17, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sum(ts_worker_memory_mib)" }
   ]
  },
  {
   "title": "Model Endpoint Access Logs",
   "type": "logs",
   "gridPos": { "h": 6, "w": 22, "x": 0, "y": 18 },
   "targets": [
    {
     "expr": "{app=\"torchserve\",container=\"torchserve\",job=\"torchserve/torchserve\",stream=\"stdout\"} |= \"ACCESS_LOG\" |= \"/predictions\""
    },
    {}
   ]
  }
 ]
}